### ISSUE TITLE
are you working?

### ISSUE THREAD

**Issue by lszcpp** [amarioguy/NTASPProjectSiteDeprecated#3]
Are you still working？

**Comment by amarioguy** [comment]
hi!

yes i'm still working on this project, sorry if the blog looks outdated i'm going to redo the blog structure once i get into the kernel debugger

**Comment by lszcpp** [comment]
oh,good lucky!

**Comment by thewindowsBoy2012** [comment]
can you tell someone to put a new discord  i get a error when i try to click on it

**Comment by thewindowsBoy2012** [comment]
can someone reopen this issue
